/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A floating, always-on-top log window driven by an external eframe
 * process. See the package README for the JS-facing usage pattern.
 */
export declare class LogWindow {
  /** Construct a handle. Does not spawn yet — call `spawn()`. */
  constructor()
  /**
   * Launch the viewer subprocess. Returns immediately; the window opens
   * asynchronously. Calling `spawn` more than once on the same handle is
   * an error — construct a fresh `LogWindow` if you need to reopen.
   */
  spawn(): void
  /**
   * Append a single message line to the viewer **and** mirror it
   * to the host process's stderr so the line is always visible in
   * the terminal too. The terminal copy keeps logs flowing for
   * `tee`/CI capture and survives the user clicking the close
   * button on the floating window.
   *
   * The viewer write is best-effort: if the viewer has already
   * been closed, the line is dropped silently instead of throwing,
   * so a dismissed window never crashes a long-running script.
   */
  log(message: string): void
  /**
   * Drop all displayed messages. Silently no-ops when the viewer
   * has already closed, matching `log()`.
   */
  clear(): void
  /**
   * `true` while execution is paused. The user pauses (and resumes)
   * by pressing the global pause hotkey shown inside the window;
   * the same hotkey also flips the viewer out of click-through mode
   * so they can drag it. Cheap O(1) lookup against the shared state.
   */
  get isPaused(): boolean
  /**
   * Block until the viewer is no longer paused. Returns immediately if not
   * currently paused. Implemented as an async task so the JS event loop
   * stays responsive while waiting.
   *
   * Returns immediately if the viewer has already closed.
   */
  waitIfPaused(): Promise<void>
  /**
   * Synchronously block the calling thread until the viewer is no
   * longer paused (or has closed). Used by `@simular-ai/simulang-js`
   * as a `setPauseHook` so every simulang-js call transparently
   * honors the pause state.
   *
   * This freezes Node's event loop while blocked — that's the
   * point: an automation script asking the OS to type, click, or
   * capture should look synchronous from the script's perspective.
   * Use `wait_if_paused()` (the async variant) instead when you
   * need timers, promises, or other JS work to keep running.
   */
  waitIfPausedSync(): void
  /**
   * Ask the viewer to close gracefully, then `wait()` for the process.
   *
   * Closing is also automatic when the parent process dies (the child sees
   * EOF on its stdin), so calling this is optional.
   */
  close(): void
}
